#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"



echo "looking for dotnet"

if command -v dotnet > /dev/null
  then
    echo "dotnet found"
  else
    echo "couldn't find dotnet please install it first"
    exit 1
fi

read -p "What is your project name? " projectName
read -p "What is your GraphEngine version? (2.0.9842) " graphEngineVersion

# Overide for testing
graphEngineVersion=${graphEngineVersion:-"2.0.9842"}

clientName=${projectName}Client
serverName=${projectName}Server
modelName=${projectName}Model

mkdir $projectName
cd $projectName

# Client Project
echo "Creating ${clientName}"

# Remove potentially old folders
rm -r $clientName
# Create a new dotnet project 
dotnet new console -o $clientName
cd $clientName

# Copy the client templates
cp -r $DIR/templates/client/. ./
# Overwrite the .csproj file generated by dotnet
mv ClientTemplate.csproj $clientName.csproj

# Replace the placeholders in the client template.
sed -i -e 's/$GRAPH_ENGINE_VERSION/'$graphEngineVersion'/g' $clientName.csproj
sed -i -e 's/$MODEL_NAME/'$modelName'/g' $clientName.csproj

# Replace the placeholder in the client program
sed -i -e 's/$NAMESPACE/'$clientName'/g' Program.cs

cd ..

echo "Finished creating ${clientName}"



# Server Project

echo "Creating ${serverName}"

rm -r $serverName

# Create a new dotnet project
dotnet new console -o $serverName
cd $serverName

# Copy the server templates
cp -r $DIR/templates/server/. ./ 

# Overwrite the .csproj file generated by dotnet
mv ServerTemplate.csproj $serverName.csproj

# Replace the placeholders in the client template.
sed -i -e 's/$GRAPH_ENGINE_VERSION/'$graphEngineVersion'/g' $serverName.csproj
sed -i -e 's/$MODEL_NAME/'$modelName'/g' $serverName.csproj

# Replace the placeholder in the server program
sed -i -e 's/$NAMESPACE/'$serverName'/g' Program.cs

cd ..

echo "Finished creating ${serverName}"



# Model Project
echo "Creating ${modelName}"

rm -r $modelName
mkdir $modelName

cd $modelName

cp -r $DIR/templates/model/. ./

cd ..

echo "Finished creating ${modelName}"

cd ..
